# Generated by Django 4.0.1 on 2022-03-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='your city', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='your state', max_length=30),
        ),
    ]
