# Generated by Django 4.0.1 on 2022-02-25 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_alter_shippingaddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.CharField(choices=[('Unapproved', 'Unapproved'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null='blank')),
                ('slug', models.SlugField(default='name', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=30)),
                ('loan_request', models.CharField(choices=[('Unapproved', 'Unapproved'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=30)),
                ('owner', models.ForeignKey(null='blank', on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
