# Generated by Django 4.0.1 on 2022-02-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Unapproved', 'Unapproved'), ('Delivered', 'Delivered')], default='Pending', max_length=30),
        ),
    ]
