# Generated by Django 4.0.1 on 2022-02-28 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_shippingaddress_guest_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestorder',
            name='customer',
        ),
        migrations.AddField(
            model_name='guestorder',
            name='guest_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_customers', to='store.customer'),
        ),
    ]
