# Generated by Django 4.0.1 on 2022-02-28 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_guestorder_customer_guestorder_guest_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestorderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.guestorder'),
        ),
    ]
