# Generated by Django 4.0.1 on 2022-02-28 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_guestorderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='guest_customer',
        ),
        migrations.AlterField(
            model_name='guestorderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
        migrations.CreateModel(
            name='GuestShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('zipcode', models.CharField(max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('guest_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_user_shipping', to='store.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
            ],
        ),
    ]
