# Generated by Django 4.0.1 on 2022-03-02 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0015_remove_shippingaddress_guest_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(default='Guest Customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_shipping', to=settings.AUTH_USER_MODEL),
        ),
    ]
