# Generated by Django 4.0.1 on 2022-03-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_shippingaddress_first_name_shippingaddress_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='order_note',
            field=models.TextField(blank=True),
        ),
    ]
