# Generated by Django 4.0.1 on 2022-03-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_guestorderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestshippingaddress',
            name='guest_customer',
        ),
    ]
